name: Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build and test (${{ matrix.network }}, ${{ matrix.optimize }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        network: [posixnet]
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - run: zig build test -freference-trace --summary all -Doptimize=${{ matrix.optimize }} -Dnetwork=${{ matrix.network }}
