name: Linux

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
          use-cache: false

      - run: rm -rf ./.zig-cache/

      - run: zig build test -freference-trace --summary all -Doptimize=Debug

      - run: rm -rf ./.zig-cache/

      - run: zig build test -freference-trace --summary all -Doptimize=ReleaseSafe

      - run: rm -rf ./.zig-cache/

      - run: zig build test -freference-trace --summary all -Doptimize=ReleaseSmall

      - run: rm -rf ./.zig-cache/

      - run: zig build test -freference-trace --summary all -Doptimize=ReleaseFast
