name: macOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and test (${{ matrix.optimize }})
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
#        network: [posix, portable]
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - run: zig build test -freference-trace --summary all -Doptimize=${{ matrix.optimize }} -Dnetwork=posix
      - run: zig build test -freference-trace --summary all -Doptimize=${{ matrix.optimize }} -Dnetwork=portable
